services:
  cups-monitor:
    build: .
    container_name: cups-status-monitor
    labels:
      - "com.centurylinklabs.watchtower.enable=false"   
    restart: unless-stopped
    environment:
      - CUPS_SERVER=localhost:631
    volumes:
      # Se CUPS usa socket Unix invece di TCP
      - /var/run/cups/cups.sock:/var/run/cups/cups.sock:ro
    network_mode: host  # Necessario per accedere a CUPS localhost
